version: '3'
services:
  archi_steam_farm:
    container_name: archi_steam_farm
    image: justarchi/archisteamfarm:released
    volumes:
      - ./archi_steam_farm_config:/app/config
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 3333:80
    depends_on:
      - archi_steam_farm
  pi_hole:
    container_name: pi_hole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
    environment:
      - TZ=America/Sao_Paulo
      - VIRTUAL_HOST=pi.hole
      - PROXY_LOCATION=pi.hole
      - ServerIP=192.0.0.1
    volumes:
      - ./pihole_storage/etc-pihole:/etc/pihole
      - ./pihole_storage/etc-dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    hostname: pi.hole
  # control_fan:
  #   container_name: control_fan
  #   build: ./control_fan
  #   devices:
  #     - /dev/gpiomem:/dev/gpiomem
  #   network_mode: "host"
  samba:
    container_name: samba
    image: servercontainers/samba
    network_mode: host
    restart: always
    hostname: storage
    cap_add:
      - CAP_NET_ADMIN
    volumes:
      - /DRIVE/share/:/shares
      - /DRIVE/avahi/:/external/avahi
    environment:
      - ACCOUNT_foouser=foopass
      - AVAHI_NAME=StorageServer
      - SAMBA_VOLUME_CONFIG_shared_home=[Share]; path=/shares;  valid users = foouser; guest ok = yes; read only = no; browseable = yes
